apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: order-service
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  source:
    repoURL: https://github.com/DongsuDanielLim/gitops.git
    targetRevision: main
    path: charts/order-service
    helm:
      valueFiles:
        - values-dev.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: order

  syncPolicy:
    automated:
      prune: true       # Git에서 삭제된 리소스 자동 삭제
      selfHeal: true    # 클러스터 변경 시 자동 복구
    syncOptions:
      - CreateNamespace=true